<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\GameServer.Core\GameServer.Core.csproj" />
		<ProjectReference Include="..\GameServer.Server\GameServer.Server.csproj" />
		<ProjectReference Include="..\GameServer.Logic\GameServer.Logic.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
	</ItemGroup>
</Project>
